In [1]:
 def gcd(a,b):                                                                                                                  
    if b==0:                                                                                                                     
        return (a,1,0)                                                                                                           
    else:                                                                                                                        
        (g,x,y) = gcd(b,a%b)                                                                                                     
        return (g,y,x - a//b*y)                                                                                                    
                                                                                                                                                                             
                                                                                                                                                                             
                                        

In [5]:
import numpy as np

A  = np.array([[1, -1],[1,0]])

In [57]:
n = 19

X = np.ones((2,n))
X[0] = np.arange(n)
X

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.]])

In [60]:
B = A @ X
inv = np.array([ gcd(n,x)[2] % n for x in range(1,n)])
inv * B[0,1:] % n  - X[0,1:]

array([ -1.,   8.,   4.,  11.,  11.,  -2.,   2.,   0.,  -6.,   8.,   2.,
         0.,   4.,  -9.,  -9.,  -2.,  -6., -16.])

In [52]:
inv = np.array([ gcd(n,x)[2] % n for x in range(1,n)])
inv

array([ 1,  7,  9, 10,  8, 11,  2,  5,  3,  4,  6, 12])

In [53]:
inv * B[0,1:] % n  - X[0,1:]

array([ -1.,   5.,   2.,   0.,   1.,  -3.,   5.,   1.,   2.,   0.,  -3.,
       -10.])

In [55]:
inv * B[0,1:] % n

array([ 0.,  7.,  5.,  4.,  6.,  3., 12.,  9., 11., 10.,  8.,  2.])

In [43]:
25 - 5 + 1

21

In [61]:
4**2 - 4 + 1

13

In [62]:
3**2 + 6 + 4

19

In [64]:
5**2 - 10 + 4

19

In [66]:
5*10 % 19

12

In [39]:
import numpy as np

W = np.exp(2J*np.pi/3)
T = np.exp(2J*np.pi/6)

In [30]:
Z = (W+2)/(W + 3)

In [42]:
Z.imag/np.sqrt(3)*14

0.9999999999999998

In [31]:
(W+3)*(W.conjugate() +3)

(7+0j)

In [38]:
Z.real*14

9.000000000000002

In [40]:
ZZ = Z = (T+ 1)/(T + 2)

In [43]:
ZZ.imag/np.sqrt(3)*14, ZZ.real*14

(0.9999999999999998, 9.0)

In [48]:
A = np.array([[1,2],[1,3]])
a = np.linalg.inv(A)
R = np.array([[1,1],[-1,0]])

In [51]:
AR = A @ R @ a

In [57]:
AR, AR @ AR 

(array([[-4.,  3.],
        [-7.,  5.]]),
 array([[-5.,  3.],
        [-7.,  4.]]))

In [64]:
A = np.array([[1,0],[2,1]])
a = np.linalg.inv(A)
R = np.array([[0,-1],[1,1]])
AR = A @ R @ a

In [65]:
AR, AR @ AR

(array([[ 2., -1.],
        [ 3., -1.]]),
 array([[ 1., -1.],
        [ 3., -2.]]))

In [1]:
def f(x,y,z):
    return x**2 + y**2 + 2*z**2 - 4*x*y*z

In [14]:
f(3,1,5), f(11,3,1)

(0, 0)