In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,0,1,4,0,0,1]).reshape(3,3)
A

array([[1, 2, 3],
       [0, 1, 4],
       [0, 0, 1]])

---

Calculer $B^{-1}$

In [3]:
B = A[1:,1:]
B

array([[1, 4],
       [0, 1]])

In [4]:
np.linalg.inv(B)

array([[ 1., -4.],
       [ 0.,  1.]])

---

Montrer que $A^{-1}$ est :

[[ 1, -2,  5],<br>
       [ 0,  1, -4],<br>
       [ 0,  0,  1]])

In [8]:
np.linalg.inv(A) 

array([[ 1., -2.,  5.],
       [ 0.,  1., -4.],
       [ 0.,  0.,  1.]])

In [10]:
-A[0,1:]@np.linalg.inv(B)

array([-2.,  5.])

---

On remarque que c'est de la forme

$\begin{pmatrix} 1 & \vec{x} \\ 0 & B^{-1}\end{pmatrix}$

Mq $\vec{x} = -[2,3].B^{-1}$.

---

Utiliser cette observation pour calculer l'inverse d'une matrice triangulaire sup de facon recursive

In [11]:
def inv_ut(U): 
    if U.shape[0] == 1: return U
    #should check its unimodular
    X = U.copy()
    BI = inv_ut(X[1:,1:])
    X[1:,1:] = inv_ut(X[1:,1:])
    X[0,1:] = -X[0,1:]@ BI

    return X

In [12]:
inv_ut(A)

array([[ 1, -2,  5],
       [ 0,  1, -4],
       [ 0,  0,  1]])

---

Ecrire un programme pour calculer la decomposition LU si elle existe sans utiliser scipy