In [2]:
 def gcd(a,b):                                                                                                                  
    if b==0:                                                                                                                     
        return (a,1,0)                                                                                                           
    else:                                                                                                                        
        (g,x,y) = gcd(b,a%b)                                                                                                     
        return (g,y,x - a//b*y)                                                                                                    
                                                                                                                                                                             
                                                                                                                                                                             
                                        

In [5]:
import numpy as np

A  = np.array([[1, -1],[1,0]])

In [30]:
X = np.ones((2,7))
X[0] = np.arange(7)
X

array([[0., 1., 2., 3., 4., 5., 6.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [38]:
B = A @ X
B

array([[-1.,  0.,  1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.]])

In [29]:
inv = np.array([ gcd(7,x)[2] % 7 for x in range(1,7)])
inv

array([1, 4, 5, 2, 3, 6])

In [39]:
inv * B[0,1:] % 7  - X[0,1:]

array([-1.,  2.,  0.,  2.,  0., -4.])

In [45]:
inv * B[0,1:] % 7

array([0., 4., 3., 6., 5., 2.])

In [43]:
25 - 5 + 1

21

In [44]:
A

array([[ 1, -1],
       [ 1,  0]])