# Splitting homology classes

$\vec{x} = \vec{h}_1 + \vec{h}_2$
 
- want all $(\vec{h}_1,\vec{h}_2)$ that are "smaller" than $\vec{x}$
- these are integer points in a parralelpiped $R$ determined by the coords of $\vec{x}$

---

## Doublons
  
- want $(\vec{h}_1,\vec{h}_2)$ but not $(\vec{h}_2,\vec{h}_1)$
- this is like taking a fundamental domain for the action of the involution $\vec{v} \mapsto \vec{x} - \vec{v}$ acting on $R$

---

## Signs of coords
  
- easy case is when all the coordinates of $\vec{x}$ are $\geq 0$
- can always reduce to this case by applying reflections in hyperplanes
- = changing the signs of the coordinates

  



In [28]:
import numpy as np
from itertools import product

X = np.array((2,1,-1,2),dtype=int)
#this is a bit of a cheat
m,n,p,q = abs(X) + 1

#all possible h_1 of a decomposition
#these are stocked as lines in a matrix 
Z = np.array(list(product(range(m),
                          range(n),
                          range(p),
                          range(q))))[1:-1] #careful if u do  m // 2

# deal with signs 
# abs(X) - X != 0 is a list of booleans
Z[:, abs(X) - X != 0] *= -1

#there will be duplicates here
# but you can deal with that 
# by taking m // 2 or something like that 
# and not doing the checking
Z #,-Z + X

array([[ 0,  0,  0,  1],
       [ 0,  0,  0,  2],
       [ 0,  0, -1,  0],
       [ 0,  0, -1,  1],
       [ 0,  0, -1,  2],
       [ 0,  1,  0,  0],
       [ 0,  1,  0,  1],
       [ 0,  1,  0,  2],
       [ 0,  1, -1,  0],
       [ 0,  1, -1,  1],
       [ 0,  1, -1,  2],
       [ 1,  0,  0,  0],
       [ 1,  0,  0,  1],
       [ 1,  0,  0,  2],
       [ 1,  0, -1,  0],
       [ 1,  0, -1,  1],
       [ 1,  0, -1,  2],
       [ 1,  1,  0,  0],
       [ 1,  1,  0,  1],
       [ 1,  1,  0,  2],
       [ 1,  1, -1,  0],
       [ 1,  1, -1,  1],
       [ 1,  1, -1,  2],
       [ 2,  0,  0,  0],
       [ 2,  0,  0,  1],
       [ 2,  0,  0,  2],
       [ 2,  0, -1,  0],
       [ 2,  0, -1,  1],
       [ 2,  0, -1,  2],
       [ 2,  1,  0,  0],
       [ 2,  1,  0,  1],
       [ 2,  1,  0,  2],
       [ 2,  1, -1,  0],
       [ 2,  1, -1,  1]])

In [29]:
-Z + X

array([[ 2,  1, -1,  1],
       [ 2,  1, -1,  0],
       [ 2,  1,  0,  2],
       [ 2,  1,  0,  1],
       [ 2,  1,  0,  0],
       [ 2,  0, -1,  2],
       [ 2,  0, -1,  1],
       [ 2,  0, -1,  0],
       [ 2,  0,  0,  2],
       [ 2,  0,  0,  1],
       [ 2,  0,  0,  0],
       [ 1,  1, -1,  2],
       [ 1,  1, -1,  1],
       [ 1,  1, -1,  0],
       [ 1,  1,  0,  2],
       [ 1,  1,  0,  1],
       [ 1,  1,  0,  0],
       [ 1,  0, -1,  2],
       [ 1,  0, -1,  1],
       [ 1,  0, -1,  0],
       [ 1,  0,  0,  2],
       [ 1,  0,  0,  1],
       [ 1,  0,  0,  0],
       [ 0,  1, -1,  2],
       [ 0,  1, -1,  1],
       [ 0,  1, -1,  0],
       [ 0,  1,  0,  2],
       [ 0,  1,  0,  1],
       [ 0,  1,  0,  0],
       [ 0,  0, -1,  2],
       [ 0,  0, -1,  1],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  2],
       [ 0,  0,  0,  1]])

In [4]:
X - Z

array([[ 2,  1, -1,  2],
       [ 2,  1, -1,  1],
       [ 2,  1,  0,  2],
       [ 2,  1,  0,  1],
       [ 2,  0, -1,  2],
       [ 2,  0, -1,  1],
       [ 2,  0,  0,  2],
       [ 2,  0,  0,  1],
       [ 1,  1, -1,  2],
       [ 1,  1, -1,  1],
       [ 1,  1,  0,  2],
       [ 1,  1,  0,  1],
       [ 1,  0, -1,  2],
       [ 1,  0, -1,  1],
       [ 1,  0,  0,  2],
       [ 1,  0,  0,  1],
       [ 0,  1, -1,  2],
       [ 0,  1, -1,  1],
       [ 0,  1,  0,  2],
       [ 0,  1,  0,  1],
       [ 0,  0, -1,  2],
       [ 0,  0, -1,  1],
       [ 0,  0,  0,  2],
       [ 0,  0,  0,  1]])