In [1]:
import numpy as np

In [3]:
def M(n):
    A = [0,1,1,n]
    return np.array(A, dtype=int).reshape(2,2)


In [4]:
A= M(1)
B = M(2)

In [5]:
A @ B @ A

array([[2, 3],
       [3, 4]])

In [8]:
MM = [M(n) for n in range(0,5)]

def word2mat(ss='01'):
    T = np.identity(2).astype(int)
    for c in ss:
        T = MM[int(c)] @ T
    return T, [int(c) for c in ss]
        

In [9]:
BB, LL = word2mat('11112212')

In [11]:
BB, LL

(array([[ 27,  44],
        [ 73, 119]]),
 [1, 1, 1, 1, 2, 2, 1, 2])

In [89]:
DD = []
for x in LL:
    Y = MM[x]
    y = Y - Y[1,1]*np.identity(2,dtype=int)
    BB = Y @ BB @ y
    DD.append(BB)
    

In [90]:
XX = np.array(DD).flatten()

In [91]:
XX.sort()

In [92]:
set(XX)

{18,
 27,
 30,
 31,
 34,
 37,
 44,
 45,
 46,
 47,
 49,
 63,
 64,
 71,
 73,
 81,
 100,
 101,
 109,
 112,
 115,
 116,
 119,
 128}

In [87]:
DD

[array([[11, 26],
        [19, 45]]),
 array([[ 7, 19],
        [18, 49]]),
 array([[13, 18],
        [31, 43]]),
 array([[12, 31],
        [17, 44]]),
 array([[10, 17],
        [27, 46]]),
 array([[19, 27],
        [26, 37]])]