# bits and pieces of code 


But is this all just "point pushing"
so that the group you get should be
just the uniformizing group(oid) of the surface


$$Q = -9(x+y)^2 + 45(y-x)^2 + 10(x-z)^2$$


### References

- thesis : https://orbilu.uni.lu/bitstream/10993/50710/1/thesis-merged.pdf
- orthotrees : https://arxiv.org/abs/2112.10694



![xx](./doan_qforms.png)

---

### The flip

$X^+ + X^- = \frac{y + z}{x - 1}(Y + Z)$ 

---

### Coeffs in flips

$(x,y,z) = ( 3,17, 21)$

1. 38/2 = 19
2. 24/16 = 3/2
3. 20/20 = 1

---


1. $X^+ + X^- = 19(Y + Z)$
1. $X^+ + X^- = \frac{3}{2}(Y + Z)$
1. $X^+ + X^- = (Y + Z)$

---

![doan's figure](./doan_fig.png)

# Objective

Calculate the hyperbolic distance between the fixed points 

```
fp_x = [19,1,1]
fp_y = [1,1.5,1]
fp_z = [1,1,1]
```

of the involutions ```gx,gy,gz``` that generate Doan's group:


one can do this using the inner product $B$ associated to the quadatic form :

$\cosh( d(u,v)) = B(u,v)$

$d(u,v) = 1/2 \ell_\gamma$ where $\gamma$ 
is the loxodromic obtained as a composition of the 
inversions in $a$ and $b$.


The length of the *companion* orthogeodesic $\gamma^*$ satisfies

$\cosh(1/2\ell_\gamma) = \sinh(1/4 \ell_\delta) \sinh(1/2 \ell_{\gamma^*})$

In [384]:
v


array([17,  3, -1])

[tt](./doan_fig.png)

![ff](./doan_fixed.png)

In [1]:
import numpy as np

In [385]:
def Q(v):
    x,y,z =v
    return x**2 + 36*y**2 + 55*z**2 - 18*x*y - 20*x*z - 90*y*z

def ip(u,v):
    # standard way to get the inner product from a q-form
    uu = np.array(u)
    vv = np.array(v)

    return .25*(Q(uu+vv)-Q(uu-vv))

def DD(v):
    # auxilliary function in Doan
    x,y,z =v
    return x**2 + y**2 + z**2 + 2*x*y*z -1

---

## Define the quadratic form or rather the associated matrix

In [3]:
MM = [1,-9,-10,-9,36,-45,-10,-45,55]
QM = np.array(MM).reshape(3,3)
QM

array([[  1,  -9, -10],
       [ -9,  36, -45],
       [-10, -45,  55]])

In [317]:
Q([17,3,-1]), DD([3,17,21])/8, [17,3,-1] @ QM @ [17,3,-1]

(360, 360.0, 360)

## Playing with Doan's generators

In [9]:
A = [-1,19,19,0,0,1,0,1,0]
gx = np.array(A).reshape(3,3)
B = [0,1,0,1,0,0,1,1,-1]
gz = np.array(B).reshape(3,3)
C = [0,0,1,3/2,-1,3/2,1,0,0]
gy = np.array(C).reshape(3,3)

In [208]:
gx, gy, gz

(array([[-1, 19, 19],
        [ 0,  0,  1],
        [ 0,  1,  0]]),
 array([[ 0. ,  0. ,  1. ],
        [ 1.5, -1. ,  1.5],
        [ 1. ,  0. ,  0. ]]),
 array([[ 0,  1,  0],
        [ 1,  0,  0],
        [ 1,  1, -1]]))

In [387]:
v = np.array([17,3,-1])
v, gx@v, gy@v

(array([17,  3, -1]), array([21, -1,  3]), array([-1., 21., 17.]))

---

## Important

so this says you get the original group back

In [392]:
L = v, gx@v, gy@v, v
for x,y in zip(L,L[1:]):
    print(x,y)
    cosh = ip(x,y)/np.sqrt(Q(x) * Q(y) )
    print(cosh)

[17  3 -1] [21 -1  3]
-3.0
[21 -1  3] [-1. 21. 17.]
-21.0
[-1. 21. 17.] [17  3 -1]
-17.0


# so this is important!

the root vector is invariant under the "commutator"
it's actually represented as a cycle in Doan's figure above

In [359]:
gy@gz@gx@v

array([17.,  3., -1.])

In [373]:
loxo = gy@gz@gx
# find the eigenvectors on the light cone
fs,fu  = [_ for _ in np.linalg.eig(loxo)[1].T if abs(Q(_)) < .00001]
# randomly pick points in the plane
a, b = fs + fu, fs - fu
nn = np.cross(fs,fu)
# find which one is on the axis of loxo in the plane
pt = [_ for _ in [a,b] if Q(_) < 0][0]
# calculate the translation length
ip(loxo@pt,pt)/np.sqrt(Q(pt) * Q(loxo@pt) )

-3.5000000000000147

In [11]:
gx.T@QM@gx - QM, gy.T@QM@gy - QM, gz.T@QM@gz - QM

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

## fixed points of the elliptics

- gx,gy,gz are diagonalisable
- 1 is an eigenvalue, the  eigenvector v satisfies Q(v) < 0 
- -1 is an eigenvalue of multiplicity 2 eigenvectors v satisfy Q(v) > 0


In [321]:
fp_x = [19,1,1]
fp_y = [1,1.5,1]
fp_z = [1,1,1]

## calculate 

the distances between the fixed points

In [322]:
L = [fp_x, fp_y, fp_z, fp_x]

traces = [ 2*ip(x,y)/np.sqrt(Q(x) * Q(y) ) for x,y in zip(L,L[1:]) ]
for x,y in zip(L,L[1:]):
    print(x,y)
    cosh = ip(x,y)/np.sqrt(Q(x) * Q(y) )
    print( 2*cosh**2 - 1 )

[19, 1, 1] [1, 1.5, 1]
23.999999999999996
[1, 1.5, 1] [1, 1, 1]
1.5000000000000004
[1, 1, 1] [19, 1, 1]
18.999999999999996


### consistent with the commutator calculation below

In [386]:
x, y, z = traces
[_**2 - 2 for _ in traces]

[47.99999999999999, 3.000000000000001, 37.99999999999999]

**there is a problem with the signs**
so it's $+xyz$ and not $-xyz$

In [345]:
x**2 + y**2 + z**2 +  x*y*z

-5.0

## this is all we really need 

to calculate to determine what the group is SO(2,1) = SL(2,R)


In [348]:
loxos = [gx@gy, gx@gz, gy@gz]
pts = [fp_y,fp_z,fp_z]


[ip(pt,(loxo)@pt)/np.sqrt(Q(pt) * Q((loxo)@pt))
for loxo, pt in zip(loxos,pts)]
    

#5**2 - 1


[-24.0, -19.0, -1.5]

---
## looking for elliptics

- gx,gy,gz are diagonalisable
- 1 is an eigenvalue eigenvector v satisfies Q(v) < 0 
- -1 is an eigenvalue of multiplicity 2 eigenvectors v satisfy Q(v) > 0


This is the **holed torus case**
it would be interesting to know 

- if in the 3 holed sphere case the corresponding involutions were reflections
- if the group we get from these elliptics is a holed torus group too

$$(u,v)_Q = \frac12(Q(u+v) - Q(u-v))$$

is an inner product if $Q$ is a quadratic form
one should be able to compute the lengths 
of the boundary geodesics from this.



In [12]:
eigenvalues, vectors = np.linalg.eig(gx)
eigenvalues

array([-1.,  1., -1.])

In [13]:
vectors

array([[ 1.        ,  0.99724137,  0.        ],
       [ 0.        ,  0.05248639, -0.70710678],
       [ 0.        ,  0.05248639,  0.70710678]])

In [14]:
gx_fp = vectors.T[1]
gx_fp = gx_fp/gx_fp[1]
gx_fp, Q(gx_fp)

(array([19.,  1.,  1.]), -360.0)

In [15]:
[Q(v) for v in vectors.T]

[1.0, -0.9917355371900829, 90.49999999999997]

In [22]:
eigenvalues, vectors = np.linalg.eig(gy)
eigenvalues
gy_fp = vectors.T[1]/vectors[0,1]
gy_fp

array([1. , 1.5, 1. ])

In [34]:
eigenvalues, vectors = np.linalg.eig(gz)
eigenvalues
[Q(v) for v in vectors.T]
gz_fp = vectors.T[1]/vectors[0,1]
Q(gz_fp)

-36.0

In [274]:
eigenvalues, ev_gxgy = np.linalg.eig(gx@gy)
eigenvalues

array([4.79791576e+01, 2.08423834e-02, 1.00000000e+00])

In [275]:
[Q(v) for v in ev_gxgy.T]

[-1.6653345369377348e-16, -7.105427357601002e-15, 61.333333333333314]

In [271]:
Q(ev_gxgy[:,2]),ev_gxgy[:,2]/ev_gxgy[0,2]

(61.333333333333314, array([ 1.,  1., -1.]))

---

# boundary geodesic on the quotient orbifold

- this element is a loop round the boundary gx@gy@gz

and we should be able to calculate it's trace using the inner product

like this

```ip(a,comm1@a)/np.sqrt(Q(a)*Q(comm1@a))```

= -3.5

In [86]:
comm = gx@gz@gy
ev_comm = np.linalg.eig(comm)

[Q(v) for v in ev_comm[1].T]
ev_comm[1].T[2]

array([-0.98313538, -0.17349448,  0.05783149])

In [85]:
ev_comm[1]

array([[ 0.99797978,  0.91654766, -0.98313538],
       [ 0.06353239,  0.39992549, -0.17349448],
       [ 0.        ,  0.        ,  0.05783149]])

In [146]:
comm1 = gx@gy@gz
comm2 = gy@gx@gz

for _ in [comm1,comm2]:
    print(np.linalg.eig(_)[0])

[6.85410197 0.14589803 1.        ]
[0.14589803 6.85410197 1.        ]


In [367]:
comm1

array([[  8.5,  75. , -27.5],
       [  0. ,   1. ,   0. ],
       [  0.5,   3. ,  -1.5]])

## These are the fixed points on the light cone

In [368]:
fp_s,fp_u = np.linalg.eig(comm1)[1].T[:2]

## calculate 
1. a point $a$ on the geodesic (plane they span)
2. the normal vector to the plane (geodesic) they span

In [369]:
a,b = fp_s + fp_u, fp_s - fp_u
normal = np.cross(a,b) # should be a multiple of (0,1,0)
Q(a), Q(b)

(-3.125829202412346, 3.1258292024123473)

### check both a and it's translate are on the geodesic

In [370]:
normal@a, normal@(comm1@a)

(0.0, 0.0)

In [ ]:
## and this is the product

In [371]:
ip(a,comm1@a)/np.sqrt(Q(a)*Q(comm1@a))

-3.4999999999999982

In [303]:
(2*3.5)

7.0

---
## check that gx_fp is on the axis of gx@gy

- ev_gxgy[:,0] ev_gxgy[:,1] are on the light cone Q = 0
- they span a plane whose intersection with the Q  = k < 0 is a geodesic
- take their  cross product and  check that gx_fp and gy_fp are orthogonal to it

In [282]:
[Q(v) for v in ev_gxgy.T[:2] ]

[-1.6653345369377348e-16, -7.105427357601002e-15]

In [278]:
gx_fp @ np.cross(ev_gxgy[:,1],ev_gxgy[:,0])

0.0

In [283]:
gy_fp @ np.cross(ev_gxgy[:,1],ev_gxgy[:,0])

-1.1102230246251565e-16

In [285]:
Q(gy_fp),Q(gx_fp)

(-45.0, -360.0)

---

##  calculation with the loxodromics

gx@gy

This is the same calculation that we did for the boundary holonomy

In [250]:
loxo = gx@gy
# find the eigenvectors on the light cone
fs,fu  = [_ for _ in np.linalg.eig(loxo)[1].T if abs(Q(_)) < .00001]
# randomly pick points in the plane
a, b = fs + fu, fs - fu
nn = np.cross(fs,fu)
# find which one is on the axis of loxo in the plane
pt = [_ for _ in [a,b] if Q(_) < 0][0]
pt = gy_fp #we could have done this
# calculate the translation length
ip(loxo@pt,pt)/np.sqrt(Q(pt) * Q(loxo@pt) )

-24.0

In [261]:
np.linalg.eig(gx)[1].T[1]/0.05248639 

array([18.99999932,  0.99999996,  0.99999996])

In [264]:
gx@fp_x + fp_x

array([0, 0, 0])

---
## eigenvectors

- two eigenvectors on the light cone 
- one on the hyperboloid

In [335]:
A = np.array([2,1,1,1]).reshape(2,2)
B = np.array([17,11,3,2]).reshape(2,2)



1.000000000000004

In [332]:
[(t, t*(19-t)- 1 )for t in range(1,10)]

[(1, 17),
 (2, 33),
 (3, 47),
 (4, 59),
 (5, 69),
 (6, 77),
 (7, 83),
 (8, 87),
 (9, 89)]

---

# References 

thesis : https://orbilu.uni.lu/bitstream/10993/50710/1/thesis-merged.pdf

orthotrees : https://arxiv.org/abs/2112.10694

https://arxiv.org/pdf/2201.07743.pdf

https://math.dartmouth.edu/~doyle/docs/heron/heron.txt

http://myslu.stlawu.edu/~svanderv/sumsquares.pdf

https://community.ams.org/journals/ecgd/2005-09-03/S1088-4173-05-00106-2/S1088-4173-05-00106-2.pdf

counting https://arxiv.org/abs/0811.2236
and also https://www.ams.org/journals/jams/2011-24-03/S0894-0347-2011-00691-7/S0894-0347-2011-00691-7.pdf

video https://www.cantorsparadise.com/circle-and-sphere-packings-from-geometry-to-number-theory-with-alex-kontorovich-cffa785e7ceb


more circle packings https://www.math.ucdavis.edu/~efuchs/LGCmain.pdf

soddy descartes https://services.math.duke.edu/~elj31/talks/ApollonianCircleIntegersPackings_20220322.pdf

soddy local -> global https://www.aimsciences.org/article/doi/10.3934/jmd.2019019


strange : https://people.math.carleton.ca/~williams/papers/pdf/352.pdf



