In [26]:
import numpy as np

A = np.array([
    [8/9, 1/18,   1/18, 0],
    [2/3, 0,   1/3, 0],
    [2/3, 1/3, 0,   0],
    [0,   0,   1,   0]
], dtype=float)

print(A)


[[0.88888889 0.05555556 0.05555556 0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.66666667 0.33333333 0.         0.        ]
 [0.         0.         1.         0.        ]]


In [29]:
S.eigenvalues

array([ 1.        ,  0.22222222, -0.33333333,  0.        ])

In [28]:
S = np.linalg.eig(A.T)
S.eigenvectors

array([[ 9.93127066e-01,  8.16496581e-01,  4.13882491e-17,
         6.32455532e-01],
       [ 8.27605889e-02, -4.08248290e-01, -7.07106781e-01,
        -7.37864787e-01],
       [ 8.27605889e-02, -4.08248290e-01,  7.07106781e-01,
        -1.05409255e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.10818511e-01]])

In [6]:
A.T

array([[0.88888889, 0.66666667, 0.66666667, 0.        ],
       [0.        , 0.        , 0.33333333, 0.        ],
       [0.11111111, 0.33333333, 0.        , 1.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [7]:
S.eigenvalues

array([ 1.        , -0.33333333,  0.22222222,  0.        ])

In [10]:
B = np.array([8/9,1/9,2/3,1/3]).reshape(2,2)

In [13]:
S = np.linalg.eig(B.T)

In [14]:
B.T @ S.eigenvectors

array([[ 0.98639392, -0.15713484],
       [ 0.16439899,  0.15713484]])

In [15]:
S.eigenvectors

array([[ 0.98639392, -0.70710678],
       [ 0.16439899,  0.70710678]])

In [16]:
S.eigenvalues

array([1.        , 0.22222222])

In [17]:
B

array([[0.88888889, 0.11111111],
       [0.66666667, 0.33333333]])

In [18]:
B - np.identity(2)

array([[-0.11111111,  0.11111111],
       [ 0.66666667, -0.66666667]])

In [20]:
B.T @ [6,1]

array([6., 1.])

In [21]:
0.98639392 / 0.16439899

5.9999998783447515

In [32]:
A.T @ [6,.5,.5,0]

array([6. , 0.5, 0.5, 0. ])

In [31]:
A

array([[0.88888889, 0.05555556, 0.05555556, 0.        ],
       [0.66666667, 0.        , 0.33333333, 0.        ],
       [0.66666667, 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ]])