In [1]:
import numpy as np

In [24]:
MM = [1,-8,-10,-8,36,-45,-10,-45,55]
MM = np.array(MM).reshape(3,3)
MM

array([[  1,  -8, -10],
       [ -8,  36, -45],
       [-10, -45,  55]])

In [32]:
A = [-1,19,19,0,0,1,0,-1,0]
A = np.array(A).reshape(3,3)
B = [0,1,0,1,0,0,1,1,-1]
B = np.array(B).reshape(3,3)

v = np.array([3,17,21])
v@(MM@v), A@v

(462, array([719,  21, -17]))

In [22]:
B@MM@B.T

array([[ 36,  -8,  73],
       [ -8,   1,   3],
       [ 73,   3, 186]])

https://arxiv.org/abs/2310.11279

Elias Dubno
Even though Zaremba's conjecture remains open, Bourgain and Kontorovich solved the problem for a full density subset. Nevertheless, there are only a handful of explicit sequences known to satisfy the strong version of the conjecture, all of which were obtained using essentially the same algorithm. In this note, we provide a refined algorithm using the folding lemma for continued fractions, which both generalizes and improves on the old one. As a result, we uncover new examples that fulfill the strong version of Zaremba's conjecture.

![xx](./folding.png)

In [8]:
def M(n):
    A = [0,1,1,n]
    return np.array(A, dtype=int).reshape(2,2)

def MM(n):
    A = [n,1,1,0]
    return np.array(A, dtype=int).reshape(2,2)

In [5]:
A= M(1)
B = M(2)

In [13]:
M(2)@MM(1) @ MM(5) @ MM(1)

array([[7, 6],
       [6, 5]])

In [15]:
MM = [M(n) for n in range(0,5)]

def word2mat(ss='01'):
    T = np.identity(2).astype(int)
    for c in ss:
        T = MM[int(c)] @ T
    return T, [int(c) for c in ss]
        

In [22]:
BB, LL = word2mat('12212')

In [23]:
BB, LL

(array([[ 7, 10],
        [19, 27]]),
 [1, 2, 2, 1, 2])

In [29]:
BB, LL = word2mat('112212')

DD = []
for x in LL:
    Y = MM[x]
    y = Y - Y[1,1]*np.identity(2,dtype=int)
    BB = Y @ BB @ y
    DD.append(BB)
XX = np.array(DD).flatten()    
XX.sort()
set(XX)

{7, 10, 11, 12, 13, 17, 18, 19, 26, 27, 31, 37, 43, 44, 45, 46, 49}

In [19]:
{4, 7, 8, 10, 11, 19, 26, 27, 30}

{18,
 27,
 30,
 31,
 34,
 37,
 44,
 45,
 46,
 47,
 49,
 63,
 64,
 71,
 73,
 81,
 100,
 101,
 109,
 112,
 115,
 116,
 119,
 128}

In [87]:
DD

[array([[11, 26],
        [19, 45]]),
 array([[ 7, 19],
        [18, 49]]),
 array([[13, 18],
        [31, 43]]),
 array([[12, 31],
        [17, 44]]),
 array([[10, 17],
        [27, 46]]),
 array([[19, 27],
        [26, 37]])]

In [21]:
AA = np.array([3,0,0,1/3]).reshape(2,2)
BB = 1/8*np.array([1,72,1/4,82]).reshape(2,2)

In [22]:
AA@BB@np.linalg.inv(AA)@np.linalg.inv(BB)

array([[-1.25      ,  9.        ],
       [-0.28472222,  1.25      ]])

In [20]:
np.linalg.det(AA)

0.0